# Generated by Django 3.1.2 on 2020-10-23 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_student1_teacher1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=264)),
            ],
        ),
        migrations.DeleteModel(
            name='Student1',
        ),
        migrations.DeleteModel(
            name='Teacher1',
        ),
        migrations.CreateModel(
            name='Student01',
            fields=[
                ('contactinfo01_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.contactinfo01')),
                ('rollno', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
            bases=('testapp.contactinfo01',),
        ),
        migrations.CreateModel(
            name='Teacher01',
            fields=[
                ('contactinfo01_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.contactinfo01')),
                ('subject', models.CharField(max_length=128)),
                ('salary', models.FloatField()),
            ],
            bases=('testapp.contactinfo01',),
        ),
    ]
